import 'dart:math' as math;
import 'dart:typed_data';

/// B3: directional-energy passive anti-spoof gate, the cheap analogue
/// of a per-orientation Gabor filter bank.
///
/// Why this exists alongside [ScreenReflectionDetector]:
///   - The reflection detector catches *colour* signatures (vivid +
///     bright pixels typical of phone-on-phone replay). It's blind to
///     monochrome / well-balanced spoof attacks — high-quality
///     printouts on matte paper, e-ink displays, etc., land inside
///     the real-skin sat/luma envelope and pass cleanly.
///   - Real skin under typical lighting has near-isotropic micro-
///     texture (pores, fine hair, follicles). Print and screen
///     attacks impose a strong directional bias: paper grain runs one
///     way, LCD sub-pixel stripes run another, dither patterns repeat
///     on a grid. Comparing high-frequency energy across orientations
///     and flagging the anisotropic case catches a class of attacks
///     the colour detector misses.
///
/// Why "Gabor" without an actual Gabor convolution: a textbook Gabor
/// energy needs a sinusoid × Gaussian envelope convolution at every
/// pixel × orientation, which is ~5-15 ms on a 112×112 crop in pure
/// Dart. Sampling 256 pixels and reading the gradient at four
/// orientations through a single-tap stencil with a fixed offset
/// approximates the same anisotropy signal at ~0.5 ms / frame. The
/// approximation loses scale selectivity (true Gabor lets you tune to
/// a specific spatial frequency); for the binary "is this isotropic
/// or not" decision we don't need it.
///
/// Stateless. Operates on the same 112×112 RGB byte buffer the
/// embedding extractor consumes, so the cost on top of the regular
/// pipeline is one pass of 256 sampled pixels × four 5-pixel-offset
/// gradient reads.
class GaborTextureDetector {
  const GaborTextureDetector();

  /// Number of pixel locations to sample. Matches
  /// [ScreenReflectionDetector] for consistency — keeps the combined
  /// passive-gate budget in the same ~1 ms order of magnitude
  /// regardless of which gate fires first.
  static const int _samples = 256;

  /// Half-window of the directional gradient stencil. A 5-pixel
  /// neighbourhood (offset ±2) targets the ~10-15 pixel-scale spatial
  /// frequencies where real-skin micro-texture lives at 112×112
  /// resolution and where screen-grid / paper-grain anisotropy is
  /// most pronounced. Smaller offsets pick up sensor noise; larger
  /// offsets drift into face-shape variance.
  static const int _stencilOffset = 2;

  /// Side length of the input crop. Hard-coded to match the embedding
  /// extractor's expected input size. The constructor does not
  /// validate this — the caller already enforces a fixed-size buffer
  /// upstream of every gate.
  static const int _side = 112;

  /// Anisotropy threshold above which a frame is flagged as
  /// texture-suspicious. Initial value chosen conservatively for the
  /// `(max - min) / (max + min)` formulation used by
  /// [scoreAnisotropy]: a well-lit isotropic-texture face measures
  /// ~0.05-0.30; pure axial-stripe attacks (LCD subpixel grid, paper
  /// grain along one axis) saturate to ~1.0; mixed-anisotropy
  /// patterns land 0.5-0.9. The default gates anything above 0.55 to
  /// bias toward real-frame acceptance. **Requires field calibration**
  /// before B2 flips PadPolicy to enforce —
  /// `verification_logs.failureReason == 'spoof'` rows generated by
  /// this gate let the calibration loop sweep the threshold without
  /// redeploying.
  static const double anisotropyThreshold = 0.55;

  /// Returns `true` when the cropped face shows texture-anisotropy
  /// statistics characteristic of a print or screen attack.
  ///
  /// Computes high-frequency directional energy at four orientations
  /// (0°, 45°, 90°, 135°), then `(max - mean) / mean` over the four
  /// energies. A frame with at least one degenerate / empty
  /// orientation (zero variance — solid colour block) is left to the
  /// upstream quality gate; this detector returns `false` rather
  /// than denying on an over-confident signal.
  ///
  /// Pure-grey or pure-black images (no texture in any direction)
  /// also short-circuit to `false`.
  bool isLikelySpoofTexture(Uint8List rgb) {
    final result = scoreAnisotropy(rgb);
    return result.score > anisotropyThreshold;
  }

  /// Computes the underlying anisotropy score and the per-orientation
  /// energies. Exposed for the calibration tooling and tests; the
  /// production hot path uses the boolean wrapper above to keep the
  /// gate's call site identical to [ScreenReflectionDetector].
  ///
  /// Score formulation: `(max - min) / (max + min + ε)` over the four
  /// directional energies. Bounded `[0, 1]`. Zero when all four
  /// orientations carry the same energy (perfectly isotropic micro-
  /// texture, the real-skin signature); approaches 1 when at least
  /// one orientation is suppressed to near-zero (the dominant
  /// signature of axial print/screen artefacts at this resolution).
  /// The earlier `(max - mean) / mean` formulation saturates at
  /// 0.33 for axial stripes — three of four directions carry
  /// equivalent energy and only the orthogonal channel zeros out —
  /// so it cannot distinguish "one direction missing" patterns from
  /// noise. The min-based form is stable against that case.
  GaborAnisotropyResult scoreAnisotropy(Uint8List rgb) {
    final expected = _side * _side * 3;
    if (rgb.length < expected) {
      return const GaborAnisotropyResult.degenerate(reason: 'input-too-small');
    }

    final stride = math.max(1, (_side * _side) ~/ _samples);
    final off = _stencilOffset;
    final minXY = off;
    final maxXY = _side - off - 1;

    // Pre-compute the luma-only view once. Reading R/G/B and computing
    // BT.601 luma per sample is fast but allocating a Float32List
    // here lets the inner gradient loop skip the per-orientation
    // colour blend. Net win on 256 samples is ~50 µs.
    final luma = Float32List(_side * _side);
    for (var i = 0, p = 0; i < luma.length; i++, p += 3) {
      luma[i] = 0.299 * rgb[p] + 0.587 * rgb[p + 1] + 0.114 * rgb[p + 2];
    }

    var energy0 = 0.0;
    var energy45 = 0.0;
    var energy90 = 0.0;
    var energy135 = 0.0;
    var taken = 0;

    for (var pi = 0; pi < luma.length && taken < _samples; pi += stride) {
      final x = pi % _side;
      final y = pi ~/ _side;
      if (x < minXY || x > maxXY || y < minXY || y > maxXY) continue;

      // Four 5-pixel-offset directional gradients. The stencil
      // diameter (2 * off) sets the spatial frequency band — see
      // [_stencilOffset] for the rationale.
      final g0 = luma[y * _side + (x + off)] - luma[y * _side + (x - off)];
      final g90 = luma[(y + off) * _side + x] - luma[(y - off) * _side + x];
      final g45 = luma[(y + off) * _side + (x + off)] -
          luma[(y - off) * _side + (x - off)];
      final g135 = luma[(y + off) * _side + (x - off)] -
          luma[(y - off) * _side + (x + off)];

      energy0 += g0 * g0;
      energy45 += g45 * g45;
      energy90 += g90 * g90;
      energy135 += g135 * g135;
      taken++;
    }

    if (taken == 0) {
      return const GaborAnisotropyResult.degenerate(reason: 'no-samples');
    }

    final maxE = math.max(
      math.max(energy0, energy45),
      math.max(energy90, energy135),
    );
    final minE = math.min(
      math.min(energy0, energy45),
      math.min(energy90, energy135),
    );

    if (maxE <= 1.0) {
      // Flat / black / saturated-white frames produce ~zero energy
      // in every direction. Returning a high anisotropy ratio from
      // tiny-over-tinier noise would deny these frames, but they
      // are already rejected upstream by the brightness gate in
      // QualityAssessor. Pass them through here.
      return const GaborAnisotropyResult.degenerate(reason: 'flat-frame');
    }

    // Bounded form: (max - min) / (max + min). The +1 in the
    // denominator is the standard FP-safety epsilon used elsewhere
    // in this pipeline (e.g. BlurMetric); for any non-degenerate
    // frame `maxE + minE` is many orders of magnitude above it, so
    // it has zero effect outside the flat-frame edge case that's
    // already short-circuited above.
    final score = (maxE - minE) / (maxE + minE + 1.0);
    return GaborAnisotropyResult.valid(
      score: score,
      energy0: energy0,
      energy45: energy45,
      energy90: energy90,
      energy135: energy135,
      samples: taken,
    );
  }
}

/// Outcome of a single [GaborTextureDetector] evaluation. Two states:
/// a [valid] result with per-orientation energies and the derived
/// anisotropy [score], or a [degenerate] result the caller should
/// treat as "no signal, pass the frame through". Calibration tooling
/// reads the `valid` payload off [verification_logs] sibling fields
/// (Phase B follow-up) to sweep the threshold against ROC data.
class GaborAnisotropyResult {
  const GaborAnisotropyResult.valid({
    required this.score,
    required this.energy0,
    required this.energy45,
    required this.energy90,
    required this.energy135,
    required this.samples,
  })  : isDegenerate = false,
        degenerateReason = null;

  const GaborAnisotropyResult.degenerate({required String reason})
      : isDegenerate = true,
        degenerateReason = reason,
        score = 0,
        energy0 = 0,
        energy45 = 0,
        energy90 = 0,
        energy135 = 0,
        samples = 0;

  /// `(max - min) / (max + min + ε)` over the four directional
  /// energies. Bounded `[0, 1]`. Zero for the perfectly isotropic
  /// case (every direction carries the same energy); approaches 1
  /// when at least one direction's energy collapses relative to the
  /// strongest. See [GaborTextureDetector.scoreAnisotropy] for why
  /// the min-based form replaced the original `(max - mean) / mean`
  /// formulation.
  final double score;
  final double energy0;
  final double energy45;
  final double energy90;
  final double energy135;
  final int samples;

  /// True when the input was unsuitable for evaluation (too small,
  /// no samples in-bounds, or a flat frame with no texture energy).
  /// Production callers should treat this as "pass" — the upstream
  /// quality + brightness gates have already had their say.
  final bool isDegenerate;

  /// Human-readable reason set on degenerate results — flows to
  /// `/debug/health` so a field operator can tell why a frame was
  /// pass-thru'd here without an interactive debugger.
  final String? degenerateReason;
}
